DROP DATABASE IF EXISTS BURGERS_DB;
CREATE DATABASE BURGERS_DB;
use BURGERS_DB;

CREATE TABLE BURGERS (
   id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
   burger VARCHAR (256) NOT NULL,
   devoured BOOLEAN NOT NULL,
   createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
